package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The Box Authorization API gives you access to authenticate and authorize an application to work with the Box APIs",
    "title": "Box 2.0 Authorization API",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "2.0"
  },
  "host": "account.box.com",
  "basePath": "/api/oauth2",
  "paths": {
    "/authorize": {
      "get": {
        "description": "The host for this api is account.box.com. This is the URL of the Box login endpoint. To begin the process of authenticating and authorizing an application to work with the Box APIs.",
        "tags": [
          "Authorization"
        ],
        "summary": "Authorize",
        "externalDocs": {
          "url": "https://docs.box.com/reference#authorize"
        },
        "operationId": "authorize",
        "parameters": [
          {
            "enum": [
              "code"
            ],
            "type": "string",
            "name": "response_type",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "scope",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Opens up the login page for authentication. Upon successful authentication process, it will be redirected to \u003cMY_REDIRECT_URI\u003e?code=\u003cMY_AUTHORIZATION_CODE\u003e"
          },
          "default": {
            "description": "Error response",
            "schema": {
              "$ref": "#/definitions/OAuthError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "OAuthError": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string"
        },
        "error_description": {
          "type": "string"
        },
        "error_uri": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      }
    }
  }
}`))
}
