package supercharged_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAbortUploadSessionParams creates a new AbortUploadSessionParams object
// with the default values initialized.
func NewAbortUploadSessionParams() AbortUploadSessionParams {
	var ()
	return AbortUploadSessionParams{}
}

// AbortUploadSessionParams contains all the bound params for the abort upload session operation
// typically these are obtained from a http.Request
//
// swagger:parameters abortUploadSession
type AbortUploadSessionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	SESSIONID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AbortUploadSessionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rSESSIONID, rhkSESSIONID, _ := route.Params.GetOK("SESSION_ID")
	if err := o.bindSESSIONID(rSESSIONID, rhkSESSIONID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AbortUploadSessionParams) bindSESSIONID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.SESSIONID = raw

	return nil
}
