package supercharged_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AbortUploadSessionHandlerFunc turns a function with the right signature into a abort upload session handler
type AbortUploadSessionHandlerFunc func(AbortUploadSessionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AbortUploadSessionHandlerFunc) Handle(params AbortUploadSessionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AbortUploadSessionHandler interface for that can handle valid abort upload session params
type AbortUploadSessionHandler interface {
	Handle(AbortUploadSessionParams, interface{}) middleware.Responder
}

// NewAbortUploadSession creates a new http.Handler for the abort upload session operation
func NewAbortUploadSession(ctx *middleware.Context, handler AbortUploadSessionHandler) *AbortUploadSession {
	return &AbortUploadSession{Context: ctx, Handler: handler}
}

/*AbortUploadSession swagger:route DELETE /files/upload_sessions/{SESSION_ID} SuperchargedUpload abortUploadSession

Abort Upload Session

Abort the upload session and discard all data uploaded. This cannot be reversed.

*/
type AbortUploadSession struct {
	Context *middleware.Context
	Handler AbortUploadSessionHandler
}

func (o *AbortUploadSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewAbortUploadSessionParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
