package supercharged_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ridewindx/loong/pkg/api/upload/models"
)

// NewCreateUploadSessionNewVersionParams creates a new CreateUploadSessionNewVersionParams object
// with the default values initialized.
func NewCreateUploadSessionNewVersionParams() CreateUploadSessionNewVersionParams {
	var ()
	return CreateUploadSessionNewVersionParams{}
}

// CreateUploadSessionNewVersionParams contains all the bound params for the create upload session new version operation
// typically these are obtained from a http.Request
//
// swagger:parameters createUploadSessionNewVersion
type CreateUploadSessionNewVersionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	FILEID string
	/*
	  Required: true
	  In: body
	*/
	Body *models.VersionUploadSessionRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateUploadSessionNewVersionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rFILEID, rhkFILEID, _ := route.Params.GetOK("FILE_ID")
	if err := o.bindFILEID(rFILEID, rhkFILEID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.VersionUploadSessionRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateUploadSessionNewVersionParams) bindFILEID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.FILEID = raw

	return nil
}
