package supercharged_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUploadSessionHandlerFunc turns a function with the right signature into a get upload session handler
type GetUploadSessionHandlerFunc func(GetUploadSessionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUploadSessionHandlerFunc) Handle(params GetUploadSessionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUploadSessionHandler interface for that can handle valid get upload session params
type GetUploadSessionHandler interface {
	Handle(GetUploadSessionParams, interface{}) middleware.Responder
}

// NewGetUploadSession creates a new http.Handler for the get upload session operation
func NewGetUploadSession(ctx *middleware.Context, handler GetUploadSessionHandler) *GetUploadSession {
	return &GetUploadSession{Context: ctx, Handler: handler}
}

/*GetUploadSession swagger:route GET /files/upload_sessions/{SESSION_ID} SuperchargedUpload getUploadSession

Upload Session Details

Return the information about this session.

*/
type GetUploadSession struct {
	Context *middleware.Context
	Handler GetUploadSessionHandler
}

func (o *GetUploadSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetUploadSessionParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
