package supercharged_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ridewindx/loong/pkg/api/upload/models"
)

// ListPartsOKCode is the HTTP code returned for type ListPartsOK
const ListPartsOKCode int = 200

/*ListPartsOK List would be successful

swagger:response listPartsOK
*/
type ListPartsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PartList `json:"body,omitempty"`
}

// NewListPartsOK creates ListPartsOK with default headers values
func NewListPartsOK() *ListPartsOK {
	return &ListPartsOK{}
}

// WithPayload adds the payload to the list parts o k response
func (o *ListPartsOK) WithPayload(payload *models.PartList) *ListPartsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list parts o k response
func (o *ListPartsOK) SetPayload(payload *models.PartList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPartsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListPartsBadRequestCode is the HTTP code returned for type ListPartsBadRequest
const ListPartsBadRequestCode int = 400

/*ListPartsBadRequest Bad request. See response body for details.

swagger:response listPartsBadRequest
*/
type ListPartsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListPartsBadRequest creates ListPartsBadRequest with default headers values
func NewListPartsBadRequest() *ListPartsBadRequest {
	return &ListPartsBadRequest{}
}

// WithPayload adds the payload to the list parts bad request response
func (o *ListPartsBadRequest) WithPayload(payload *models.Error) *ListPartsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list parts bad request response
func (o *ListPartsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPartsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListPartsDefault Upload commit error

swagger:response listPartsDefault
*/
type ListPartsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListPartsDefault creates ListPartsDefault with default headers values
func NewListPartsDefault(code int) *ListPartsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListPartsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list parts default response
func (o *ListPartsDefault) WithStatusCode(code int) *ListPartsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list parts default response
func (o *ListPartsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list parts default response
func (o *ListPartsDefault) WithPayload(payload *models.Error) *ListPartsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list parts default response
func (o *ListPartsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPartsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
