package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OAuthError o auth error
// swagger:model OAuthError
type OAuthError struct {

	// error
	Error string `json:"error,omitempty"`

	// error description
	ErrorDescription string `json:"error_description,omitempty"`

	// error uri
	ErrorURI string `json:"error_uri,omitempty"`

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this o auth error
func (m *OAuthError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OAuthError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuthError) UnmarshalBinary(b []byte) error {
	var res OAuthError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
