package access_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ridewindx/loong/pkg/api/token/models"
)

// GenerateAccessTokenOKCode is the HTTP code returned for type GenerateAccessTokenOK
const GenerateAccessTokenOKCode int = 200

/*GenerateAccessTokenOK A new access token is returned.

swagger:response generateAccessTokenOK
*/
type GenerateAccessTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccessToken `json:"body,omitempty"`
}

// NewGenerateAccessTokenOK creates GenerateAccessTokenOK with default headers values
func NewGenerateAccessTokenOK() *GenerateAccessTokenOK {
	return &GenerateAccessTokenOK{}
}

// WithPayload adds the payload to the generate access token o k response
func (o *GenerateAccessTokenOK) WithPayload(payload *models.AccessToken) *GenerateAccessTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the generate access token o k response
func (o *GenerateAccessTokenOK) SetPayload(payload *models.AccessToken) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GenerateAccessTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GenerateAccessTokenDefault Access token generation error

swagger:response generateAccessTokenDefault
*/
type GenerateAccessTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.OAuthError `json:"body,omitempty"`
}

// NewGenerateAccessTokenDefault creates GenerateAccessTokenDefault with default headers values
func NewGenerateAccessTokenDefault(code int) *GenerateAccessTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &GenerateAccessTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the generate access token default response
func (o *GenerateAccessTokenDefault) WithStatusCode(code int) *GenerateAccessTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the generate access token default response
func (o *GenerateAccessTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the generate access token default response
func (o *GenerateAccessTokenDefault) WithPayload(payload *models.OAuthError) *GenerateAccessTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the generate access token default response
func (o *GenerateAccessTokenDefault) SetPayload(payload *models.OAuthError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GenerateAccessTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
