package file_upload

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUploadFileVersionParams creates a new UploadFileVersionParams object
// with the default values initialized.
func NewUploadFileVersionParams() UploadFileVersionParams {
	var ()
	return UploadFileVersionParams{}
}

// UploadFileVersionParams contains all the bound params for the upload file version operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadFileVersion
type UploadFileVersionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: path
	*/
	FILEID string
	/*This is in the ‘etag’ field of the file object
	  In: header
	*/
	IfMatch *string
	/*File attributes
	  In: formData
	*/
	Attributes *string
	/*File to upload
	  Required: true
	  In: formData
	*/
	File runtime.File
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UploadFileVersionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	rFILEID, rhkFILEID, _ := route.Params.GetOK("FILE_ID")
	if err := o.bindFILEID(rFILEID, rhkFILEID, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindIfMatch(r.Header[http.CanonicalHeaderKey("If-Match")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	fdAttributes, fdhkAttributes, _ := fds.GetOK("attributes")
	if err := o.bindAttributes(fdAttributes, fdhkAttributes, route.Formats); err != nil {
		res = append(res, err)
	}

	file, fileHeader, err := r.FormFile("file")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "file", err))
	} else {
		o.File = runtime.File{Data: file, Header: fileHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UploadFileVersionParams) bindFILEID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.FILEID = raw

	return nil
}

func (o *UploadFileVersionParams) bindIfMatch(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.IfMatch = &raw

	return nil
}

func (o *UploadFileVersionParams) bindAttributes(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Attributes = &raw

	return nil
}
