package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RestrictedTo restricted to
// swagger:model RestrictedTo
type RestrictedTo struct {

	// object
	Object *FileReference `json:"object,omitempty"`

	// scope
	Scope string `json:"scope,omitempty"`
}

// Validate validates this restricted to
func (m *RestrictedTo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RestrictedTo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestrictedTo) UnmarshalBinary(b []byte) error {
	var res RestrictedTo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
