package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PartList part list
// swagger:model PartList
type PartList struct {

	// An array of parts
	Entries []*Part `json:"entries"`

	// The limit that was used for these entries. This will be the same as the limit query parameter unless that value exceeded the maximum value allowed.
	Limit int32 `json:"limit,omitempty"`

	// The 0-based offset of the first entry in this set. This will be the same as the offset query parameter.
	Offset int32 `json:"offset,omitempty"`

	// This will always be equal to the number of expected parts in the session (i.e. ceiling(file size / part size)).
	TotalCount int32 `json:"total_count,omitempty"`
}

// Validate validates this part list
func (m *PartList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntries(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartList) validateEntries(formats strfmt.Registry) error {

	if swag.IsZero(m.Entries) { // not required
		return nil
	}

	for i := 0; i < len(m.Entries); i++ {

		if swag.IsZero(m.Entries[i]) { // not required
			continue
		}

		if m.Entries[i] != nil {

			if err := m.Entries[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entries" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartList) UnmarshalBinary(b []byte) error {
	var res PartList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
