package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SharedLink shared link
// swagger:model SharedLink
type SharedLink struct {

	// access
	Access string `json:"access,omitempty"`

	// download count
	DownloadCount int64 `json:"download_count,omitempty"`

	// download url
	DownloadURL string `json:"download_url,omitempty"`

	// effective access
	EffectiveAccess string `json:"effective_access,omitempty"`

	// is password enabled
	IsPasswordEnabled bool `json:"is_password_enabled,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// permissions
	Permissions *SharedLinkPermissions `json:"permissions,omitempty"`

	// preview count
	PreviewCount int64 `json:"preview_count,omitempty"`

	// unshared at
	UnsharedAt string `json:"unshared_at,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// vanity url
	VanityURL string `json:"vanity_url,omitempty"`
}

// Validate validates this shared link
func (m *SharedLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermissions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SharedLink) validatePermissions(formats strfmt.Registry) error {

	if swag.IsZero(m.Permissions) { // not required
		return nil
	}

	if m.Permissions != nil {

		if err := m.Permissions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("permissions")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SharedLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SharedLink) UnmarshalBinary(b []byte) error {
	var res SharedLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
