package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UploadPartResponse upload part response
// swagger:model UploadPartResponse
type UploadPartResponse struct {

	// part
	Part *Part `json:"part,omitempty"`
}

// Validate validates this upload part response
func (m *UploadPartResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UploadPartResponse) validatePart(formats strfmt.Registry) error {

	if swag.IsZero(m.Part) { // not required
		return nil
	}

	if m.Part != nil {

		if err := m.Part.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("part")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UploadPartResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadPartResponse) UnmarshalBinary(b []byte) error {
	var res UploadPartResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
