package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WatermarkInfo watermark info
// swagger:model WatermarkInfo
type WatermarkInfo []*WatermarkInfoItems0

// Validate validates this watermark info
func (m WatermarkInfo) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// WatermarkInfoItems0 watermark info items0
// swagger:model WatermarkInfoItems0
type WatermarkInfoItems0 struct {

	// is watermarked
	IsWatermarked bool `json:"is_watermarked,omitempty"`
}

// Validate validates this watermark info items0
func (m *WatermarkInfoItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WatermarkInfoItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WatermarkInfoItems0) UnmarshalBinary(b []byte) error {
	var res WatermarkInfoItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
